### ISSUE TITLE
Task List Sample

### ISSUE THREAD

**Issue by MashimoR** [MashimoR/github-releases-practice#5]
- [x] MashimoR/github-releases-practice#2
- [ ] MashimoR/github-releases-practice#3
- [ ] MashimoR/github-releases-practice#4
